sudo: false
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
script: "
  if [ ${TRAVIS_PULL_REQUEST} = 'false' ]; 
  then
    echo \"== MAIN build ==\";
    ./gradlew test uploadArchives;
  else
    echo \"== PULL build ==\";
    ./gradlew test;
  fi
"
jdk:
- oraclejdk8
env:
  global:
  - secure: H5D+dQ4BH263Zbw56vZU1j6gZgzPaL5DvQKuPUj9dPFJZGkSflCyLCcOJKMoXwp9m8xUQJ1+5cIhCa06IwiV54dleZC0tcI72mfTQ9ZTiRixEGAwgcfgnAoQunVRHL+bkqUeUB+kK5Gcf9YDWUpSdGJYiuVO2zJqMifnFxbnF5w=
  - secure: eMPyAUFD6IlEwAdU1KM3OQt8klQI8wR2bijK8whQfoNF5CyjkoDVi/YEo5GtNzmcGujkREhN0IzIHCmJDUYWzzU/71sakibpo1iajQsKm+gBtHb5TYXRmHGPJeXQv8AT2YL+q6Z97UU0m0VnoOU7I/oJxOoiJ9d5XYPV40IpjaM=
